"""
HELIOS CFO Digital Twin — Executive Dashboards
==============================================

A single Streamlit app that renders five role-specific views over the same
warehouse, plus a Scenario Lab and the conversational CFO assistant. The point
of one app with five lenses (rather than five apps) is the FP&A reality: every
audience reads the *same* numbers, but each cares about a different slice and
altitude. CFO wants margin bridges and cash; CEO wants growth and the moonshot
burn; the Board wants governance-grade trend and capital allocation; Department
heads want their cost line; Investors want the metrics that move a multiple.

Every figure on screen is computed by the analytics engine (kpis / variance /
compare / forecasting) — the UI never does finance math itself.
Run:  PYTHONPATH=. python -m streamlit run app/streamlit_app.py
"""

from __future__ import annotations

# Streamlit Cloud runs this file directly, so the repo root is not on sys.path and
# `src.*` imports fail. Put it there before any first-party import, and build the
# gold layer on first boot if the (gitignored) warehouse artifact isn't present.
import sys, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
if not (ROOT / "data" / "gold_monthly.parquet").exists():
    subprocess.run([sys.executable, "-m", "src.warehouse.build_warehouse"],
                   cwd=ROOT, check=True)

import altair as alt
import pandas as pd
import streamlit as st

from src.analytics.kpis import quarterly, compute_kpis, KPI_BY_AUDIENCE
from src.analytics.variance import revenue_bridge, comp_bridge, pl_variance
from src.scenarios.compare import compare
from src.forecasting.pipeline import ensemble_forecast
from src.narration.cfo_assistant import ask

st.set_page_config(page_title="HELIOS · CFO Digital Twin", layout="wide",
                   page_icon="◆")

NAVY = "#0B1F3A"
GOLD = "#C9A227"
TEAL = "#2A9D8F"
RED = "#C44536"
GREY = "#6B7280"

st.markdown(
    f"""
    <style>
      .stApp {{ background: #0d1117; }}
      h1,h2,h3,h4 {{ color: #e6edf3; }}
      .metric-card {{
        background:{NAVY}; border:1px solid #1d2d44; border-radius:14px;
        padding:14px 18px; }}
      .stMetric {{ background:#11192a; border:1px solid #1d2d44;
        border-radius:14px; padding:10px 14px; }}
      [data-testid="stMetricValue"] {{ color:#e6edf3; }}
      [data-testid="stMetricLabel"] {{ color:#9bb0c9; }}
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_data
def load_gold() -> pd.DataFrame:
    return pd.read_parquet("data/gold_monthly.parquet")


@st.cache_data
def kpis_for(scenario: str) -> pd.DataFrame:
    df = load_gold()
    return compute_kpis(quarterly(df[df.scenario == scenario]))


def _fmt_b(x: float) -> str:
    if x is None or pd.isna(x):
        return "—"
    a = abs(x)
    if a >= 1e9:
        return f"${x/1e9:.2f}B"
    if a >= 1e6:
        return f"${x/1e6:.0f}M"
    return f"${x:,.0f}"


def line(df, y, title, fmt="$,.0f", color=GOLD):
    d = df.copy()
    d["q"] = d["quarter"]
    ch = (
        alt.Chart(d)
        .mark_line(point=True, color=color, strokeWidth=3)
        .encode(
            x=alt.X("q:N", title=None, axis=alt.Axis(labelColor="#9bb0c9")),
            y=alt.Y(f"{y}:Q", title=None, axis=alt.Axis(format=fmt, labelColor="#9bb0c9")),
            tooltip=["quarter", alt.Tooltip(f"{y}:Q", format=fmt)],
        )
        .properties(height=240, title=title)
        .configure_view(strokeWidth=0)
        .configure(background="#0d1117")
        .configure_title(color="#e6edf3", fontSize=14)
    )
    st.altair_chart(ch, use_container_width=True)


# --------------------------------------------------------------------------- #
# Sidebar
# --------------------------------------------------------------------------- #
df = load_gold()
scenarios = sorted(df.scenario.unique().tolist())
st.sidebar.title("◆ HELIOS")
st.sidebar.caption("CFO Digital Twin · AI-powered financial OS")
view = st.sidebar.radio(
    "View",
    ["CFO", "CEO", "Board", "Department", "Investor", "Scenario Lab", "CFO Assistant"],
)
scn = st.sidebar.selectbox("Plan track", scenarios,
                           index=scenarios.index("Reported actuals")
                           if "Reported actuals" in scenarios else 0)
st.sidebar.markdown("---")
st.sidebar.caption("Synthetic company **HELIOS** — a two-segment tech analog: "
                   "**Platform** (ads + cloud/AI-API) funds **Frontier** "
                   "(AR/AI-device moonshot). All figures generated by a "
                   "driver-based three-statement model.")

k = kpis_for(scn)
latest = k.iloc[-1]


# --------------------------------------------------------------------------- #
# CFO
# --------------------------------------------------------------------------- #
if view == "CFO":
    st.title("CFO Dashboard")
    st.caption(f"Track: **{scn}** · latest quarter **{latest.quarter}**")
    c = st.columns(5)
    c[0].metric("Revenue", _fmt_b(latest.revenue), f"{latest.revenue_yoy*100:.1f}% YoY")
    c[1].metric("Operating margin", f"{latest.operating_margin*100:.1f}%")
    c[2].metric("FCF margin", f"{latest.fcf_margin*100:.1f}%")
    c[3].metric("Rule of 40", f"{latest.rule_of_40:.0f}")
    c[4].metric("Cash", _fmt_b(latest.cash))

    a, b = st.columns(2)
    with a:
        line(k, "operating_margin", "Operating margin", fmt="%", color=GOLD)
        line(k, "fcf", "Free cash flow", color=TEAL)
    with b:
        line(k, "revenue", "Revenue", color=GOLD)
        line(k, "frontier_operating_income", "Frontier segment operating income", color=RED)

    st.subheader(f"Revenue vs Plan — bridge · {latest.quarter}")
    rb = revenue_bridge(latest.quarter)["totals"]
    bcols = st.columns(4)
    bcols[0].metric("Variance", _fmt_b(rb["variance"]))
    bcols[1].metric("Volume", _fmt_b(rb["volume"]))
    bcols[2].metric("Price", _fmt_b(rb["price"]))
    bcols[3].metric("FX", _fmt_b(rb["fx"]))
    st.caption("Volume / Price / FX foot exactly to the ads-revenue variance "
               "(three-factor decomposition, rescaled to reconcile).")

    st.subheader(f"P&L vs Plan · {latest.quarter}")
    st.dataframe(pl_variance(latest.quarter), use_container_width=True, hide_index=True)


# --------------------------------------------------------------------------- #
# CEO
# --------------------------------------------------------------------------- #
elif view == "CEO":
    st.title("CEO Dashboard")
    st.caption(f"Track: **{scn}** · latest quarter **{latest.quarter}**")
    c = st.columns(5)
    c[0].metric("Revenue", _fmt_b(latest.revenue), f"{latest.revenue_yoy*100:.1f}% YoY")
    c[1].metric("Platform OI", _fmt_b(latest.platform_operating_income))
    c[2].metric("Frontier burn", _fmt_b(latest.frontier_operating_income))
    c[3].metric("Headcount", f"{latest.headcount_total:,.0f}")
    c[4].metric("Rev / head", _fmt_b(latest.revenue_per_head))

    a, b = st.columns(2)
    with a:
        line(k, "revenue", "Revenue", color=GOLD)
        line(k, "platform_operating_income", "Platform operating income (the engine)", color=TEAL)
    with b:
        line(k, "headcount_total", "Headcount", fmt=",.0f", color=GREY)
        line(k, "frontier_operating_income", "Frontier burn (the moonshot)", color=RED)
    st.info("Strategic tension HELIOS exists to manage: Platform throws off "
            "cash; Frontier consumes a growing share of it. The CEO view tracks "
            "whether the engine is outrunning the moonshot.")


# --------------------------------------------------------------------------- #
# Board
# --------------------------------------------------------------------------- #
elif view == "Board":
    st.title("Board Dashboard")
    st.caption(f"Track: **{scn}** · governance-grade trend")
    c = st.columns(4)
    c[0].metric("Revenue (LTQ)", _fmt_b(latest.revenue), f"{latest.revenue_yoy*100:.1f}% YoY")
    c[1].metric("Operating margin", f"{latest.operating_margin*100:.1f}%")
    c[2].metric("CapEx % rev", f"{latest.capex_pct_revenue*100:.1f}%")
    c[3].metric("SBC % rev", f"{latest.sbc_pct_revenue*100:.1f}%")
    a, b = st.columns(2)
    with a:
        line(k, "operating_margin", "Operating margin", fmt="%", color=GOLD)
        line(k, "capex_pct_revenue", "CapEx intensity (AI-infra build)", fmt="%", color=TEAL)
    with b:
        line(k, "rule_of_40", "Rule of 40", fmt=".0f", color=GOLD)
        line(k, "sbc_pct_revenue", "Stock-based comp intensity", fmt="%", color=RED)
    st.subheader("Capital allocation snapshot")
    st.dataframe(
        k[["quarter", "revenue", "fcf", "capex", "sbc"]].tail(6),
        use_container_width=True, hide_index=True,
    )


# --------------------------------------------------------------------------- #
# Department
# --------------------------------------------------------------------------- #
elif view == "Department":
    st.title("Department Dashboard")
    hc_cols = [c for c in df.columns if c.startswith("hc_")]
    funcs = [c[3:] for c in hc_cols]
    fn = st.selectbox("Function", funcs)
    sub = df[df.scenario == scn].copy()
    sub["q"] = sub["quarter"]
    g = sub.groupby("quarter").agg(headcount=(f"hc_{fn}", "last")).reset_index()
    st.metric(f"{fn} headcount (latest)", f"{g.headcount.iloc[-1]:,.0f}")
    line(g, "headcount", f"{fn} headcount", fmt=",.0f", color=TEAL)
    st.subheader(f"Comp bridge (company) · {latest.quarter}")
    cb = comp_bridge(latest.quarter)["totals"]
    cc = st.columns(3)
    cc[0].metric("Comp variance", _fmt_b(cb["variance"]))
    cc[1].metric("Headcount effect", _fmt_b(cb["headcount_effect"]))
    cc[2].metric("Rate effect", _fmt_b(cb["rate_effect"]))
    st.caption("Comp variance splits into a headcount (volume) effect and a "
               "rate (avg-comp) effect per function, footing to total.")


# --------------------------------------------------------------------------- #
# Investor
# --------------------------------------------------------------------------- #
elif view == "Investor":
    st.title("Investor Dashboard")
    c = st.columns(5)
    c[0].metric("Revenue", _fmt_b(latest.revenue), f"{latest.revenue_yoy*100:.1f}% YoY")
    c[1].metric("Rule of 40", f"{latest.rule_of_40:.0f}")
    c[2].metric("NRR", f"{latest.nrr*100:.0f}%")
    c[3].metric("FCF margin", f"{latest.fcf_margin*100:.1f}%")
    c[4].metric("Magic number", f"{latest.magic_number:.2f}")
    a, b = st.columns(2)
    with a:
        line(k, "revenue_yoy", "Revenue growth (YoY)", fmt="%", color=GOLD)
        line(k, "nrr", "Net revenue retention", fmt="%", color=TEAL)
    with b:
        line(k, "rule_of_40", "Rule of 40", fmt=".0f", color=GOLD)
        line(k, "fcf_margin", "FCF margin", fmt="%", color=TEAL)
    st.subheader("6-month ensemble forecast — revenue")
    with st.spinner("Running walk-forward backtest + ensemble…"):
        fc = ensemble_forecast(df[df.scenario == scn].sort_values("date"),
                               target="revenue", h=6)
    st.write(f"Backtest WAPE by model: "
             + ", ".join(f"{m}: {v:.3f}" for m, v in fc["backtest_wape"].items()))
    st.write("Ensemble weights: "
             + ", ".join(f"{m}: {w:.2f}" for m, w in fc["weights"].items()))
    fdf = pd.DataFrame({"month": fc["future_dates"],
                        "revenue": fc["ensemble"],
                        "lo95": fc["lower_95"], "hi95": fc["upper_95"],
                        "lo80": fc["lower_80"], "hi80": fc["upper_80"]})
    base_x = alt.X("month:N", title=None)
    band95 = alt.Chart(fdf).mark_area(color=GOLD, opacity=0.12).encode(
        x=base_x, y=alt.Y("lo95:Q", title=None, axis=alt.Axis(format="$,.0f")),
        y2="hi95:Q")
    band80 = alt.Chart(fdf).mark_area(color=GOLD, opacity=0.22).encode(
        x=base_x, y="lo80:Q", y2="hi80:Q")
    center = alt.Chart(fdf).mark_line(color=GOLD, point=True).encode(
        x=base_x, y="revenue:Q")
    st.altair_chart(
        (band95 + band80 + center).properties(height=260)
        .configure(background="#0d1117")
        .configure_axis(labelColor="#9bb0c9"),
        use_container_width=True,
    )
    st.caption("Shaded areas: ~80% and ~95% confidence bands "
               "(backtest residual spread × horizon, widened by model disagreement).")


# --------------------------------------------------------------------------- #
# Scenario Lab
# --------------------------------------------------------------------------- #
elif view == "Scenario Lab":
    st.title("Scenario Lab")
    st.caption("Each what-if reruns the full driver-based three-statement model "
               "vs Base Plan. Deltas are full-year (final modeled year).")
    comp = compare(df)
    show = comp[["scenario", "revenue_delta_pct", "operating_income_delta_pct",
                 "op_margin_base", "op_margin_scn", "headcount_total_delta",
                 "frontier_operating_income_delta"]].copy()
    show.columns = ["Scenario", "Rev Δ%", "OI Δ%", "Op margin (base)",
                    "Op margin (scn)", "Headcount Δ", "Frontier OI Δ"]
    st.dataframe(show, use_container_width=True, hide_index=True)
    pick = st.selectbox("Inspect a scenario", comp.scenario.tolist())
    row = comp[comp.scenario == pick].iloc[0]
    c = st.columns(4)
    c[0].metric("Revenue Δ", _fmt_b(row.revenue_delta), f"{row.revenue_delta_pct*100:.1f}%")
    c[1].metric("Operating income Δ", _fmt_b(row.operating_income_delta),
                f"{row.operating_income_delta_pct*100:.1f}%")
    c[2].metric("Op margin", f"{row.op_margin_scn*100:.1f}%",
                f"{(row.op_margin_scn-row.op_margin_base)*100:.1f} pp")
    c[3].metric("Headcount Δ", f"{row.headcount_total_delta:,.0f}")
    st.info("Look at **Economic recession**: revenue falls modestly but "
            "operating income collapses — operating leverage running in reverse, "
            "the single most important thing a recession scenario should teach.")


# --------------------------------------------------------------------------- #
# CFO Assistant
# --------------------------------------------------------------------------- #
elif view == "CFO Assistant":
    st.title("Conversational CFO Assistant")
    st.caption("Architecture: **code computes, the model narrates.** The "
               "assistant assembles an evidence pack from the warehouse, then "
               "explains it. It never invents a number.")
    q = st.text_input("Ask a finance question",
                      "Why did revenue change this quarter?")
    qtr = st.selectbox("Quarter", sorted(df.quarter.unique().tolist()),
                       index=len(df.quarter.unique()) - 1)
    backend = st.radio("Backend", ["template", "llm"], horizontal=True,
                       help="template = deterministic, zero-dep. "
                            "llm = routes through Claude (needs ANTHROPIC_API_KEY).")
    if st.button("Ask", type="primary"):
        with st.spinner("Assembling evidence + narrating…"):
            st.markdown(ask(q, quarter=qtr, backend=backend))
    st.markdown("---")
    st.caption("Try: *explain the variance* · *how is budget performance* · "
               "*where can we optimize cost* · *what changed in the forecast*")
